config/routes.rb
Rails.application.routes.draw do
  get 'calendario/index'
  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  resources :registers
  resources :users
  resources :people
  resources :rols

  post 'users/habilitar'
  post 'users/deshabilitar'

  get 'reporte1', to: 'registers#reporteCH'
  post 'reporte1', to: 'registers#reporteCH'
  post 'registers/cantidadHoras'
  post 'registers/prueba'
  
  get 'calendario', to: 'calendario#index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :user
  

end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  load_and_authorize_resource
  #before_action :set_register, only: %i[ show edit update destroy ]
  
  def reporteCH
    @anios = (2018..2021)
    @id = params[:id]
  end
  
  def prueba
    puts "METODO DE PRUEBA DESDE EL CONTROLADOR"
    
    #Parámetros elegidos
    @user_id = params[:user_id]
    @month = Integer(params[:mes_id])
    @year = Integer(params[:anio_id])
    
    #Consulta: todos los registros que están dentro de ese rango
    @range = Date.new(@year, @month)
    @registers = Register.joins(:user).where(  users: {id:@user_id} , registers:{fecha: @range.all_month})
    
    @totalMes = 0
    @lista = {}

    if @registers.length > 0
      puts "SE ENCONTRARON REGISTROS"
      
      (1..31).each do |day|
        @entrada = 0
        @salida = 0

        @registers.each do |item|
          if item.fecha.day == day
              if item.tipo == 'E'
                @entrada = Time.parse(item.hora.strftime("%I:%M %p"))
              end
              if item.tipo == 'S'
                @salida = Time.parse(item.hora.strftime("%I:%M %p"))
              end
          end
        end
        @totalHoras = @salida.hour - @entrada.hour
        @totalMes += @totalHoras

        @lista.store(:"#{day}", @totalHoras)
        
      end
      @lista.each do |key, value|
        puts "El día #{key} trabajaste #{value} horas"
      end
    else
      puts "NO SE ENCONTRARON REGISTROS"
    end
 
    respond_to do |format|
      format.js {render 'reporteCH'}
    end

  end
  

  def cantidadHoras

    @user_id = params[:user_id]
    @month = Integer(params[:mes_id])
    @year = Integer(params[:anio_id])

    @range = Date.new(@year, @month)
    @registers = Register.joins(:user).where(  users: {id:@user_id} , registers:{fecha: @range.all_month})
    
    @totalMes = 0

    if @registers.length > 0
      puts "SE ENCONTRARON REGISTROS"
      
      (1..31).each do |day|
        @entrada = 0
        @salida = 0

        @registers.each do |item|
          if item.fecha.day == day
              if item.tipo == 'E'
                @entrada = Time.parse(item.hora.strftime("%I:%M %p"))
              end
              if item.tipo == 'S'
                @salida = Time.parse(item.hora.strftime("%I:%M %p"))
              end
              puts "AQUI ESTOY #{item.hora} - #{item.tipo}"
          end
        end

        @totalHoras = @salida.hour - @entrada.hour
        @totalMes += @totalHoras
        puts "***************************************"
        puts " El día #{day} trabajaste  #{@totalHoras} horas"
        puts "***************************************"
        
      end

    else
      puts "NO SE ENCONTRARON REGISTROS"
    end
#
#
    #(1..31).each do |day|
#
    #  @entrada = 0
    #  @salida = 0
#
    #  @registers.each do |item|
    #    if item.fecha.day == day
    #        if item.tipo == 'E'
    #          @entrada = Time.parse(item.hora.strftime("%I:%M %p"))
    #        end
    #        if item.tipo == 'S'
    #          @salida = Time.parse(item.hora.strftime("%I:%M %p"))
    #        end
#
    #        puts "AQUI ESTOY #{item.hora} - #{item.tipo}"
    #    end
#
    #  end
    #  
    #  @totalHoras = @salida.hour - @entrada.hour
    #  @totalMes += @totalHoras
    #  puts "***************************************"
    #  puts " El día #{day} trabajaste  #{@totalHoras} horas"
    #  puts "***************************************"
    #end
    
#
    #@registers.each do |item|
    #  puts item.hora
#
    #  if item.tipo == 'E'
    #      @entrada = Time.parse(item.hora.strftime("%I:%M %p"))
    #  end
    #  if item.tipo == 'S'
    #      @salida = Time.parse(item.hora.strftime("%I:%M %p"))
    #  end
    #  
    #end
#
    #@tiempoTotal = (@salida.hour*60 + @salida.min) - (@entrada.hour*60 + @entrada.min)
    #@totalHoras = @salida.hour - @entrada.hour
    #@totalMin =  @salida.min+@entrada.min
#
    #puts "***************************************"
    #puts " Trabajaste #{@totalHoras}:#{@totalMin < 10 ? "0#{@totalMin}":@totalMin} horas"
    #puts "***************************************"
#
  end



  # GET /registers or /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1 or /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
    @session = session[:user_id]
    @register.id = @session
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers or /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: "Register was successfully created." }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1 or /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: "Register was successfully updated." }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1 or /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: "Register was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #Nuevos métodos

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def register_params
      params.require(:register).permit(:fecha, :hora, :tipo, :user_id)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_with(model: register, local: true) do |form| %>
  <% if register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field mb-3">
    <%= form.label :fecha, class:"form-label my-1" %>
    <div class="d-flex inp">
      <%= form.date_select :fecha%>
    </div>
  </div>

  <div class="field mb-3">
    <%= form.label :hora, class:"form-label my-1" %>
    <div class="d-flex inp align-items-center" >
      <%= form.time_select :hora %>
    </div>

  </div>

  <div class="field mb-3">
    <%= form.label :tipo , class:"form-label my-1"%>
    <div class="form-check d-flex align-items-center">
      <%= form.radio_button :tipo, 'E', class:"form-check-input", id:"flexRadioDefault2" %>
      <label class="form-check-label mx-2" for="flexRadioDefault2">
        Entrada
      </label>
    </div>
     <div class="form-check d-flex align-items-center">
      <%= form.radio_button :tipo, 'S', class:"form-check-input", id:"flexRadioDefault3" %>
      <label class="form-check-label mx-2" for="flexRadioDefault3">
        Salida
      </label>
    </div>

  </div>

  <div class="field mb-3">
    <%= form.text_field :user_id, :value=> @session, class:"form-control", type:'hidden' %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-success w-100" %>
  </div>
<% end %>

app/views/registers/_register.html.erb
<tr>
    <th scope="row"><%= register.id %></th>
    <th scope="row"><%= register.tipo =='S' ? 'Salida':'Entrada' %></th>
    <th scope="row"><%= register.fecha %></th>
    <th scope="row"><%= register.hora.strftime("%I:%M %p") %></th>
    <th scope="row"> </th>
</tr>

app/views/registers/edit.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Editar Registros</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to @register, class: "btn btn-light text-center mx-2 text-black" do %>
         <i class="bi bi-eye-fill"></i>
          Ver
        <% end %>
        <%= link_to registers_path, class: "btn btn-dark text-center mx-2 text-white", title:"Atrás" do %>
          <i class="bi bi-arrow-90deg-left"></i>
        <% end %>
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
        <%= render 'form', register: @register %>       
  </div>
</div>

app/views/registers/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Lista de Registros</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to new_register_path, class: "btn btn-light text-center mx-2 text-black" do %>
         <i class="bi bi-plus-lg"></i>
          Nuevo
        <% end %>
        <a href="/menu" class="btn btn-dark text-white" title="Atrás"> 
          <i class="bi bi-arrow-90deg-left"></i>
        </a> 
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
    <div class="table-responsive bg-white p-3 rounded-3">

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Tipo</th>
            <th>Empleado</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @registers.each do |register| %>

            <% if current_user.rol.id == 3 %>
              <!--ROL: ADMIN-->
              <tr>
                <td><%= register.id %></td>
                <td><%= register.fecha %></td>
                <td><%= register.hora.strftime("%I:%M %p") %></td>
                <td><%= register.tipo == 'E'? 'Entrada':'Salida' %></td>
                <td>
                  <%= register.user.person.nombres %>
                  <%= register.user.person.apellidoPat %>
                  <%= register.user.person.apellidoMat %>
                </td>
                <td>
                  <%= link_to register, class: "btn btn-success text-white" do %>
                    <i class="bi bi-eye-fill"></i>
                  <%  end  %>
                  
                </td>
                
              </tr>
            <% else %>
              <!--ROL: EMPLEADO-->

              <% if register.user.id == current_user.id %>
                <tr>
                  <td><%= register.id %></td>
                  <td><%= register.fecha %></td>
                  <td><%= register.hora.strftime("%I:%M %p") %></td>
                  <td><%= register.tipo== 'E'? 'Entrada':'Salida' %></td>
                  <td>
                      <%= register.user.person.nombres %>
                      <%= register.user.person.apellidoPat %>
                      <%= register.user.person.apellidoMat %>
                  </td>
                  <td>
                    <%= link_to register, class: "btn btn-success text-white" do %>
                      <i class="bi bi-pencil-square"></i>
                    <%  end  %>
                  </td>
                  <td>
                    <%= link_to edit_register_path(register), class: "btn btn-warning" do%>
                      <i class="bi bi-eye-fill"></i>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to register,class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="bi bi-x-square"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>



  

app/views/registers/new.html.erb
<div class="list">
    <div class="header">
        <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
            <h1 class="text-white">Nuevo Registro</h1>
            <div class="d-flex justify-content-around">
                <%= link_to registers_path, class:"btn btn-dark text-white", title:"Atrás" do %>
                    <i class="bi bi-arrow-90deg-left"></i>
                <% end %>
            </div>
        </div>
    </div>
    <div class="container mx-auto py-4">
        <%= render 'form', register: @register, class:"form-reg" %>
    </div>
</div>

app/views/registers/reporteCH.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">REPORTE</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to users_path, class: "btn btn-dark text-center mx-2 text-white", title:"Atrás" do %>
          <i class="bi bi-arrow-90deg-left"></i>
        <% end %>
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
    <div class="w-50 mx-auto my-4 card ">
        <div class="card-header">
          Horas trabajadas por mes
        </div>
        <div class="card-body">

          <%= form_with(url: registers_prueba_path, id:'form-prueba', data: { type: :json }, class:"m-0 p-0 w-100", local: false)  do |form| %>
            <div class="d-flex justify-content-between w-100">
                <%= form.select(:mes_id, {}, {}, {class:"form-select w-50"}) do%>
                  <option value="1">Enero</option>
                  <option value="2">Febrero</option>
                  <option value="3">Marzo</option>
                  <option value="4">Abril</option>
                  <option value="5">Mayo</option>
                  <option value="6">Junio</option>
                  <option value="7">Julio</option>
                  <option value="8">Agosto</option>
                  <option value="9">Septiembre</option>
                  <option value="10">Octubre</option>
                  <option value="11">Noviembre</option>
                  <option value="12">Diciembre</option>
                <% end %>
                <%= form.select(:anio_id, {}, {}, {class:"form-select w-50 mx-2"}) do%>
                  <% @anios.each do |c| -%>
                    <%= content_tag(:option, c, value: c) %>
                  <% end %>
                <% end %>

                <div class="field mb-3">
                  <%= form.text_field :user_id, :value=> @id , class:"form-control", type:'hidden' %>
                </div>

                <%= form.submit "Buscar", class:"btn btn-success px-3", id:"btn-submit"%>
                

            </div>
          
          <% end %> 

          <div class="mt-3">

            <div class="border-top py-2 d-flex justify-content-between">
                <table class="table">
                  <thead>
                      <tr>
                      <th scope="col">#</th>
                      <th scope="col">Tipo</th>
                      <th scope="col">Fecha</th>
                      <th scope="col">Hora</th>
                      <th scope="col">TOTAL</th>
                      </tr>
                  </thead>
                  <tbody id="box-prueba">
                     
                  </tbody>
              </table>
            </div>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/registers/reporteCH.js.erb
console.log("<%= @lista %>")

app/views/registers/show.html.erb
<div class="container py-4 mx-auto">
  <div class="row my-4">
    <div class="card w-50 mx-auto p-0">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 id="notice">Información general</h5>
         <%= link_to registers_path,  class:"btn btn-dark text-white", title:"Atrás" do %>
            <i class="bi bi-arrow-90deg-left"></i>
          <% end %>
      </div>
      <div class="card-body">
        
        <p class="card-text mb-3">
          <strong>Fecha:</strong>
          <%= @register.fecha %>
        </p>

        <p class="card-text mb-3">
          <strong>Hora:</strong>
          <%= @register.hora %>
        </p>

        <p class="card-text mb-3">
          <strong>Tipo:</strong>
          <%= @register.tipo=='E'?'Entrada':'Salida' %>
        </p>

        <p class="card-text mb-3">
          <strong>Empleado:</strong>
          <%= @register.user.person.nombres %>
          <%= @register.user.person.apellidoPat %> 
          <%= @register.user.person.apellidoMat %> 
        </p>

        <div class="actions d-flex justify-content-end">
          <% if current_user.rol.id == 4 %>

            <%= link_to edit_register_path(@register), class:"btn btn-success text-white px-4"  do%> 
              <i class="bi bi-pencil-square"></i>
              Editar
            <% end %>

          <% end %>
         
        </div>
      </div>
    </div>
  </div>
</div>