config/routes.rb
Rails.application.routes.draw do
  get 'calendario/index'
  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  resources :registers
  resources :users
  resources :people
  resources :rols

  post 'users/habilitar'
  post 'users/deshabilitar'

  get 'reporte1', to: 'registers#reporteCH'
  post 'reporte1', to: 'registers#reporteCH'
  post 'registers/cantidadHoras'
  post 'registers/prueba'
  
  get 'calendario', to: 'calendario#index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource
  
  #before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:nombres, :apellidoPat, :apellidoMat, :dni)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidoPat %>
    <%= form.text_field :apellidoPat %>
  </div>

  <div class="field">
    <%= form.label :apellidoMat %>
    <%= form.text_field :apellidoMat %>
  </div>

  <div class="field">
    <%= form.label :dni %>
    <%= form.text_field :dni %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4">
      <h1 class="text-white">Lista de empleados</h1>
    </div>
  </div>


  <div class="container mx-auto py-4">
      <p id="notice"><%= notice %></p>

      
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombres</th>
            <th>Apellidopat</th>
            <th>Apellidomat</th>
            <th>Dni</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @people.each do |person| %>
            <tr>
              <td><%= person.id %></td>
              <td><%= person.nombres %></td>
              <td><%= person.apellidoPat %></td>
              <td><%= person.apellidoMat %></td>
              <td><%= person.dni %></td>
              <td><%= link_to 'Ver', person %></td>
              <td><%= link_to 'Editar', edit_person_path(person) %></td>
              <td><%= link_to 'Eliminar', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      <%= link_to 'Nuevo empleado', new_person_path %>
      
  </div>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @person.nombres %>
</p>

<p>
  <strong>Apellidopat:</strong>
  <%= @person.apellidoPat %>
</p>

<p>
  <strong>Apellidomat:</strong>
  <%= @person.apellidoMat %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @person.dni %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>