config/routes.rb
Rails.application.routes.draw do
  get 'calendario/index'
  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  resources :registers
  resources :users
  resources :people
  resources :rols

  post 'users/habilitar'
  post 'users/deshabilitar'

  get 'reporte1', to: 'registers#reporteCH'
  post 'reporte1', to: 'registers#reporteCH'
  post 'registers/cantidadHoras'
  post 'registers/prueba'
  
  get 'calendario', to: 'calendario#index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :rol
  belongs_to :person
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  
  #before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end
  
  # GET /users/1 or /users/1.json
  def show
  end
  
  # GET /users/new
  def new
    @user = User.new
    @roles = Rol.all
    @people = Person.all

  
  end

  # GET /users/1/edit
  def edit
    @roles = Rol.all
    @people = Person.all
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @roles = Rol.all
    @people = Person.all

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    @roles = Rol.all
    @people = Person.all
  end

  def habilitar
    @user = User.find(params[:id])
    @user.update_attribute(:estado, true)
    redirect_to users_path
  end
  
  def deshabilitar
    @user = User.find(params[:id])
    @user.update_attribute(:estado, false)
    redirect_to users_path
  end



  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :estado, :rol_id, :person_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= form_with(model: user, local: true) do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field mb-3">
        <%= form.label 'Nombre de usuario' , class:"form-label my-1" %>
        <%= form.text_field :username, class:"form-control" %>
      </div>

      <div class="field mb-3">
        <%= form.label 'Contraseña' , class:"form-label my-1" %>
        <%= form.password_field :password, class:"form-control" %>
      </div>

      <div class="field mb-3">
        <%= form.label 'Confirmación de contraseña' , class:"form-label my-1" %>
        <%= form.password_field :password_confirmation, class:"form-control" %>
      </div>

      <div class="form-check mb-3 d-flex align-items-center px-0">
        <label class="form-check-label mr-2" for="user_estado">
          Estado
        </label>
          <%= form.check_box :estado, class:"mx-2" %>
      </div>


      <div class="field mb-3">
        <label class="form-check-label mr-2 my-1" for="user_rol_id">
          Rol
        </label>

        <%= form.select(:rol_id) do%>
          <% @roles.each do |c| -%>
            <%= content_tag(:option, c.descripcion, value: c.id) %>
          <% end %>
        <% end %>
            
      </div>

       <div class="field mb-3">
        <label class="form-check-label mr-2 my-1" for="user_rol_id">
          Empleado
        </label>

        <%= form.select(:person_id, options = {class:"form-select"} )  do%>
          <% @people.each do |c| -%>
            <%= content_tag(:option, c.nombres+ ' ' + c.apellidoPat + ' ' + c.apellidoMat, value: c.id) %>
          <% end %>
        <% end %>
            
      </div>

      <div class="actions">
        <%= form.submit "Guardar", class:"btn btn-success w-100" %>
      </div>
    <% end %>

app/views/users/edit.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Editar usuarios</h1>
    
      <div class="d-flex justify-content-around">
        <%= link_to @user, class: "btn btn-light text-center mx-2 text-black" do %>
         <i class="bi bi-eye-fill"></i>
          Ver
        <% end %>
        <%= link_to users_path, class: "btn btn-dark text-center mx-2 text-white", title:"Atrás" do %>
          <i class="bi bi-arrow-90deg-left"></i>
        <% end %>
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
        <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
      <h1 class="text-white">Lista de Usuarios</h1>
      <div class="d-flex justify-content-around">
        <%= link_to new_user_path(@user), class: "btn btn-light text-center mx-2 text-black" do%>
          <i class="bi bi-plus-lg"></i>
          Nuevo
        <% end %>
        <a href="/menu" class="btn btn-dark text-white" title="Atrás"> 
          <i class="bi bi-arrow-90deg-left"></i>
        </a> 
      </div>
    </div>
  </div>


  <div class="container mx-auto py-4">
      
    <p id="notice"><%= notice %></p>
    <div class="table-responsive bg-white p-3 rounded-3">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nombre de usuario</th>
            <th>Estado</th>
            <th>Rol</th>
            <th>Empleado</th>
            <th colspan="6"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.username %></td>
              <td><%= user.estado ? 'Activo':'Inactivo'   %></td>
              <td><%= user.rol.descripcion %></td>
              <td><%= user.person.nombres%> <%= user.person.apellidoPat%> <%= user.person.apellidoMat%> </td>
              <td>
                <%= link_to user, class: "btn btn-success text-white" do %>
                  <i class="bi bi-eye-fill"></i>
                <% end %>
              </td>
              <td>
                <%= link_to edit_user_path(user) , class: "btn btn-warning" do%>
                  <i class="bi bi-pencil-square"></i>
                <% end %>
              </td>
              <td>
                <%= link_to user,class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Are you sure?' } do%>
                      <i class="bi bi-x-square"></i>
                <% end%>
              
              </td>

              <% if user.estado %>

              <td>
                  <%= link_to users_deshabilitar_path(:id => user.id), method: :post, class: "btn btn-dark text-white", title:"Inabilitar" do%>
                    <i class="bi bi-stop-circle"></i>
                  <% end %>

                </td>
              <% else %>
                <td>
                  <%= link_to users_habilitar_path(:id => user.id), method: :post,  class: "btn btn-info text-dark", title:"Habilitar" do%>
                    <i class="bi bi-play-circle"></i>
                  <% end %>
                </td>
              <% end %>
              <td>
                  <%= link_to  reporte1_path(:id => user.id),  :class => "btn btn-secondary text-white", title: "Horas de trabajo" do %>
                    <i class="bi bi-clock-fill"></i>
                  <%  end  %>
              </td>
              <td>
                  <%= link_to  calendario_path(:id => user.id),  :class => "btn btn-primary text-white", title: "Calendario" do %>
                    <i class="bi bi-calendar-fill"></i>
                  <%  end  %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
      <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered mx-auto">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Reporte</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            
              
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="list">
    <div class="header">
        <div class="container mx-auto py-4 d-flex justify-content-between align-items-center">
            <h1 class="text-white">Nuevo Usuario</h1>
            <div class="d-flex justify-content-around">
                <%= link_to users_path, class:"btn btn-dark text-white", title:"Atrás" do %>
                    <i class="bi bi-arrow-90deg-left"></i>
                <% end %>
            </div>
        </div>
    </div>
    <div class="container mx-auto py-4">
        <%= render 'form', user: @user, class:"form-reg" %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container py-4 mx-auto">
  <div class="row my-4">
    <div class="card w-50 mx-auto p-0">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 id="notice">Información general</h5>
         <%= link_to users_path,  class:"btn btn-dark text-white", title:"Atrás" do %>
            <i class="bi bi-arrow-90deg-left"></i>
          <% end %>
      </div>
      <div class="card-body">
        
        <p class="card-text mb-3">
            <strong>Nombre de usuario:</strong>
            <%= @user.username %>
        </p>

        <p class="card-text mb-3">
          <strong>Estado:</strong>
          <%= @user.estado ? 'Activo':'Inactivo' %>
        </p>

        <p class="card-text mb-3">
          <strong>Rol:</strong>
          <%= @user.rol.descripcion %>
        </p>
        <p class="card-text mb-3">
          <strong>Empleado:</strong>
          <%= @user.person.nombres %>
          <%= @user.person.apellidoPat %> 
          <%= @user.person.apellidoMat %> 
        </p>

        <div class="actions d-flex justify-content-end">

            <%= link_to edit_user_path(@user), class:"btn btn-success text-white px-4"  do%> 
              <i class="bi bi-pencil-square"></i>
              Editar
            <% end %>
         
        </div>
      </div>
    </div>
  </div>
</div>