config/routes.rb
Rails.application.routes.draw do
  get 'calendario/index'
  get 'menu', to: 'menu#index' #Mostrar el menú
  get 'login', to: 'sessions#new' #Mostrar el formulario
  post 'login', to: 'sessions#create' #Crear la sesión
  get 'logout', to: 'sessions#destroy'
  
  resources :registers
  resources :users
  resources :people
  resources :rols

  post 'users/habilitar'
  post 'users/deshabilitar'

  get 'reporte1', to: 'registers#reporteCH'
  post 'reporte1', to: 'registers#reporteCH'
  post 'registers/cantidadHoras'
  post 'registers/prueba'
  
  get 'calendario', to: 'calendario#index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rol.rb
class Rol < ApplicationRecord
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  load_and_authorize_resource
  
  #before_action :set_rol, only: %i[ show edit update destroy ]

  # GET /rols or /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1 or /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols or /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: "Rol was successfully created." }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1 or /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: "Rol was successfully updated." }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1 or /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: "Rol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rol_params
      params.require(:rol).permit(:descripcion)
    end
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/views/rols/_form.html.erb
<%= form_with(model: rol, local: true) do |form| %>
  <% if rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
      <% rol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rols/edit.html.erb
<h1>Editing Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Show', @rol %> |
<%= link_to 'Back', rols_path %>

app/views/rols/index.html.erb
<div class="list">
  <div class="header">
    <div class="container mx-auto py-4">
      <h1 class="text-white">Lista de roles</h1>
    </div>
  </div>


  <div class="container mx-auto py-4">
      <p id="notice"><%= notice %></p>

      
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>Descripción</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @rols.each do |rol| %>
            <tr>
                <td><%= rol.id %></td>
                <td><%= rol.descripcion %></td>
                <td><%= link_to 'Ver', rol %></td>
                <td><%= link_to 'Editar', edit_rol_path(rol) %></td>
                <td><%= link_to 'Eliminar', rol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      <!--<%= link_to 'Nuevo rol', new_rol_path %>-->     
  </div>
</div>

app/views/rols/new.html.erb
<h1>New Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Back', rols_path %>

app/views/rols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @rol.descripcion %>
</p>

<%= link_to 'Edit', edit_rol_path(@rol) %> |
<%= link_to 'Back', rols_path %>